[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.install]
cmds = ["pip install --upgrade pip"]

[start]
cmd = "cd apps/api && gunicorn property_live_api:app --host 0.0.0.0 --port $PORT --workers $GUNICORN_WORKERS --worker-class uvicorn.workers.UvicornWorker --timeout 120"
