[build]
builder = "NIXPACKS"
buildCommand = "npm install && cd apps/api && pip install -r requirements.txt"

[deploy]
numReplicas = 1
startCommand = "cd apps/api && python -m uvicorn main_simple:app --host 0.0.0.0 --port ${PORT:-8000}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[environments.production]
numReplicas = 2
startCommand = "cd apps/api && python -m uvicorn main_simple:app --host 0.0.0.0 --port ${PORT:-8000} --workers 4"

[[services]]
name = "api"
type = "web"
port = 8000

[[services]]
name = "web"
type = "web"
port = 5173
buildCommand = "cd apps/web && npm install && npm run build"
startCommand = "cd apps/web && npm run preview --port ${PORT:-5173}"