/**
 * MetricCard Component
 * ====================
 *
 * Generated by Nano Banana Design Agent (Google AI Studio)
 *
 * A reusable metric card for displaying analytics data on dashboards.
 * Shows a single metric with label, value, icon, and optional trend indicator.
 *
 * Features:
 * - Multiple sizes (sm, md, lg)
 * - Trend indicators with color coding
 * - Premium/highlighted mode with gold accent
 * - Loading skeleton state
 * - Click handler support
 * - WCAG 2.2 AA compliant
 */

import React from 'react';
import {
  ArrowUp,
  ArrowDown,
  LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * Props for the MetricCard component.
 */
export interface MetricCardProps {
  /** The label/title for the metric (e.g., "Total Properties"). */
  label: string;
  /** The main value of the metric (e.g., "9,113,150", "$325,000"). */
  value: string | number;
  /** The Lucide icon component representing the metric type. */
  icon: LucideIcon;
  /** Optional percentage change value. Positive for up, negative for down. */
  comparisonValue?: number;
  /** Optional data for a sparkline/mini chart (placeholder for now). */
  sparklineData?: number[];
  /** The size of the card: 'sm', 'md', or 'lg'. Defaults to 'md'. */
  size?: 'sm' | 'md' | 'lg';
  /** If true, the card will be highlighted with the premium Gold accent color. */
  isGold?: boolean;
  /** If true, the card will display a loading skeleton state. */
  isLoading?: boolean;
  /** Additional CSS class names to apply to the card wrapper. */
  className?: string;
  /** Optional click handler for the card. */
  onClick?: () => void;
  /** Aria label for accessibility. */
  ariaLabel?: string;
}

/**
 * MetricCardSkeleton displays a loading state for the metric card.
 */
export const MetricCardSkeleton: React.FC<{ size?: 'sm' | 'md' | 'lg' }> = ({ size = 'md' }) => {
  const cardPadding = {
    sm: 'p-3',
    md: 'p-4',
    lg: 'p-5',
  };

  return (
    <div
      className={cn(
        'relative flex flex-col justify-between rounded-lg border border-neutral-200',
        'bg-white shadow-sm animate-pulse',
        cardPadding[size]
      )}
      role="status"
      aria-label="Loading metric"
    >
      <div className="flex items-center justify-between mb-2">
        <div className="h-4 w-2/3 bg-neutral-200 rounded" />
        <div className="h-5 w-5 bg-neutral-200 rounded" />
      </div>
      <div className="h-8 w-1/2 bg-neutral-200 rounded mb-2" />
      <div className="h-4 w-1/4 bg-neutral-200 rounded" />
    </div>
  );
};

/**
 * MetricCard displays a single metric with label, value, icon, and trend indicator.
 */
export const MetricCard: React.FC<MetricCardProps> = ({
  label,
  value,
  icon: Icon,
  comparisonValue,
  sparklineData,
  size = 'md',
  isGold = false,
  isLoading = false,
  className,
  onClick,
  ariaLabel,
}) => {
  if (isLoading) {
    return <MetricCardSkeleton size={size} />;
  }

  const isPositive = comparisonValue !== undefined && comparisonValue > 0;
  const isNegative = comparisonValue !== undefined && comparisonValue < 0;

  // Trend color based on value
  const trendColorClass = isPositive
    ? 'text-[#0ABAB5]'
    : isNegative
    ? 'text-red-500'
    : 'text-neutral-500';

  const TrendIcon = isPositive ? ArrowUp : ArrowDown;

  // Size-based styling
  const cardPadding = {
    sm: 'p-3',
    md: 'p-4',
    lg: 'p-5',
  };

  const labelClasses = {
    sm: 'text-xs',
    md: 'text-sm',
    lg: 'text-base',
  };

  const valueClasses = {
    sm: 'text-xl font-semibold',
    md: 'text-2xl font-semibold',
    lg: 'text-3xl font-bold',
  };

  const comparisonClasses = {
    sm: 'text-xs',
    md: 'text-sm',
    lg: 'text-base',
  };

  const iconSize = {
    sm: 16,
    md: 20,
    lg: 24,
  };

  // Default aria-label
  const defaultAriaLabel =
    ariaLabel ||
    `${label}: ${value}${
      comparisonValue !== undefined
        ? `, change of ${comparisonValue.toFixed(1)} percent`
        : ''
    }`;

  return (
    <div
      className={cn(
        'relative flex flex-col justify-between rounded-lg border',
        'bg-white shadow-sm transition-all duration-200 ease-out',
        'hover:shadow-md hover:bg-neutral-50/50',
        isGold
          ? 'border-[#D4AF37] hover:border-[#D4AF37]/80'
          : 'border-neutral-200',
        cardPadding[size],
        onClick && 'cursor-pointer',
        className
      )}
      role={onClick ? 'button' : 'status'}
      aria-label={defaultAriaLabel}
      onClick={onClick}
      tabIndex={onClick ? 0 : -1}
      onKeyDown={(e) => {
        if (onClick && (e.key === 'Enter' || e.key === ' ')) {
          e.preventDefault();
          onClick();
        }
      }}
    >
      {/* Header: Label and Icon */}
      <div className="flex items-center justify-between mb-2">
        <p className={cn('text-neutral-600 font-medium', labelClasses[size])}>
          {label}
        </p>
        {Icon && (
          <Icon
            className={cn(
              'text-neutral-400',
              isGold && 'text-[#D4AF37]'
            )}
            size={iconSize[size]}
            aria-hidden="true"
          />
        )}
      </div>

      {/* Metric Value */}
      <p className={cn('text-neutral-900', valueClasses[size])}>{value}</p>

      {/* Comparison and Sparkline */}
      <div className="flex items-end justify-between mt-2 gap-2">
        {comparisonValue !== undefined && (
          <div
            className={cn(
              'flex items-center gap-1',
              trendColorClass,
              comparisonClasses[size]
            )}
          >
            <TrendIcon
              size={iconSize[size] * 0.7}
              className="inline-block"
              aria-hidden="true"
            />
            <span>
              {`${isPositive ? '+' : ''}${comparisonValue.toFixed(1)}%`}
            </span>
          </div>
        )}

        {sparklineData && sparklineData.length > 0 && (
          <div
            className={cn(
              'flex-grow h-8 rounded-md overflow-hidden',
              isGold
                ? 'bg-gradient-to-r from-[#D4AF37]/20 to-[#D4AF37]/40'
                : 'bg-[#0ABAB5]/10',
              size === 'sm' && 'h-6',
              size === 'lg' && 'h-10'
            )}
            aria-hidden="true"
          >
            {/* Sparkline visualization */}
            <svg
              viewBox={`0 0 ${sparklineData.length * 10} 100`}
              className="w-full h-full"
              preserveAspectRatio="none"
            >
              <polyline
                points={sparklineData
                  .map((v, i) => {
                    const max = Math.max(...sparklineData);
                    const min = Math.min(...sparklineData);
                    const range = max - min || 1;
                    const y = 100 - ((v - min) / range) * 80 - 10;
                    return `${i * 10 + 5},${y}`;
                  })
                  .join(' ')}
                fill="none"
                stroke={isGold ? '#D4AF37' : '#0ABAB5'}
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
        )}
      </div>
    </div>
  );
};

export default MetricCard;
