/**
 * PropertyCard Component
 * ======================
 *
 * Generated by Nano Banana Design Agent (Google AI Studio)
 *
 * A reusable property card component for the ConcordBroker platform.
 * Displays key property information with modern styling and accessibility.
 *
 * Features:
 * - Property address and image display
 * - Market value (just_value) prominently shown
 * - Owner name and parcel ID
 * - Property type and status badges
 * - Favorite/bookmark functionality
 * - Loading skeleton state
 * - Mobile-first responsive design
 * - WCAG 2.2 AA compliant
 */

import React from 'react';
import { Heart } from 'lucide-react';
import { cn } from '@/lib/utils';

/**
 * Formats a number as USD currency.
 */
function formatCurrency(value: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}

/**
 * Defines the possible property types.
 */
export type PropertyType = 'residential' | 'commercial' | 'vacant land';

/**
 * Defines the possible property statuses.
 */
export type PropertyStatus = 'active' | 'pending' | 'sold';

/**
 * Props for the PropertyCard component.
 */
export interface PropertyCardProps {
  /** The unique identifier for the property parcel. */
  parcelId: string;
  /** The full street address of the property. */
  streetAddress: string;
  /** The city where the property is located. */
  city: string;
  /** The state where the property is located (e.g., "FL"). */
  state: string;
  /** The zip code of the property. */
  zipCode: string;
  /** The market value of the property. */
  justValue: number;
  /** The name of the current owner. */
  ownerName: string;
  /** The URL of the property image. If not provided, a placeholder will be shown. */
  imageUrl?: string;
  /** The type of the property. */
  propertyType: PropertyType;
  /** The current status of the property listing. */
  status: PropertyStatus;
  /** Indicates if the property is marked as a favorite by the user. */
  isFavorite: boolean;
  /** Indicates if the property is a premium/featured listing. Defaults to false. */
  isPremium?: boolean;
  /** Callback function when the card is clicked. Receives the parcelId. */
  onClick: (parcelId: string) => void;
  /** Callback when the favorite button is toggled. Receives parcelId and new state. */
  onToggleFavorite: (parcelId: string, isFavorite: boolean) => void;
  /** Loading state. If true, skeleton loader will be displayed. Defaults to false. */
  isLoading?: boolean;
}

/**
 * PropertyCardSkeleton displays a loading state for the property card.
 */
export const PropertyCardSkeleton: React.FC = () => (
  <div
    className="relative w-full lg:max-w-xs bg-white rounded-lg p-0
               border border-neutral-200 overflow-hidden
               shadow-sm flex flex-col animate-pulse"
    role="status"
    aria-live="polite"
    aria-label="Loading property card"
  >
    <div className="w-full h-40 bg-neutral-200" />
    <div className="p-4 flex flex-col space-y-3 flex-grow">
      <div className="h-6 bg-neutral-200 rounded-md w-3/4" />
      <div className="h-4 bg-neutral-200 rounded-md w-1/2" />
      <div className="flex items-center space-x-2">
        <div className="h-4 bg-neutral-200 rounded-full w-1/3" />
        <div className="h-4 bg-neutral-200 rounded-full w-1/4" />
      </div>
      <div className="h-4 bg-neutral-200 rounded-md w-2/3" />
      <div className="h-4 bg-neutral-200 rounded-md w-1/2" />
    </div>
    <div className="absolute top-4 right-4 h-8 w-8 rounded-full bg-neutral-200" />
  </div>
);

/**
 * PropertyCard displays key information about a property.
 * Designed for ConcordBroker, adhering to brand guidelines and design principles.
 */
export const PropertyCard: React.FC<PropertyCardProps> = ({
  parcelId,
  streetAddress,
  city,
  state,
  zipCode,
  justValue,
  ownerName,
  imageUrl,
  propertyType,
  status,
  isFavorite,
  isPremium = false,
  onClick,
  onToggleFavorite,
  isLoading = false,
}) => {
  if (isLoading) {
    return <PropertyCardSkeleton />;
  }

  const fullAddress = `${streetAddress}, ${city}, ${state} ${zipCode}`;

  // Status badge colors using ConcordBroker brand palette
  const statusColors: Record<PropertyStatus, string> = {
    active: 'bg-[#0ABAB5]/10 text-[#0ABAB5] border-[#0ABAB5]/30',
    pending: 'bg-amber-100 text-amber-700 border-amber-300',
    sold: 'bg-red-100 text-red-700 border-red-300',
  };

  // Property type badge colors
  const propertyTypeColors: Record<PropertyType, string> = {
    residential: 'bg-blue-100 text-blue-700 border-blue-300',
    commercial: 'bg-purple-100 text-purple-700 border-purple-300',
    'vacant land': 'bg-green-100 text-green-700 border-green-300',
  };

  const handleCardClick = () => onClick(parcelId);

  const handleFavoriteClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    onToggleFavorite(parcelId, !isFavorite);
  };

  return (
    <div
      className={cn(
        "relative w-full lg:max-w-xs bg-white rounded-lg cursor-pointer",
        "border border-neutral-200 overflow-hidden",
        "shadow-sm hover:shadow-md",
        "hover:-translate-y-0.5 transition-all duration-200 ease-out",
        "flex flex-col",
        isPremium && "border-2 border-[#D4AF37] ring-1 ring-[#D4AF37]/20"
      )}
      onClick={handleCardClick}
      role="link"
      tabIndex={0}
      aria-label={`View details for property at ${fullAddress}, valued at ${formatCurrency(justValue)}`}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          handleCardClick();
        }
      }}
    >
      {/* Property Image or Placeholder */}
      <div className="w-full h-40 bg-neutral-100 flex items-center justify-center overflow-hidden">
        {imageUrl ? (
          <img
            src={imageUrl}
            alt={`Property at ${fullAddress}`}
            className="w-full h-full object-cover"
            loading="lazy"
          />
        ) : (
          <span className="text-neutral-400 text-sm italic p-4 text-center">
            No image available
          </span>
        )}
      </div>

      {/* Content Section */}
      <div className="p-4 flex flex-col gap-2 flex-grow">
        {/* Value - Prominently displayed */}
        <p
          className={cn(
            "font-bold text-2xl",
            isPremium ? "text-[#D4AF37]" : "text-[#0ABAB5]"
          )}
        >
          {formatCurrency(justValue)}
        </p>

        {/* Address */}
        <p className="text-neutral-800 text-base line-clamp-2 font-medium">
          {fullAddress}
        </p>

        {/* Badges for Property Type and Status */}
        <div className="flex flex-wrap gap-2 py-1">
          <span
            className={cn(
              "text-xs font-semibold px-2 py-1 rounded-full border",
              propertyTypeColors[propertyType]
            )}
          >
            {propertyType.charAt(0).toUpperCase() + propertyType.slice(1)}
          </span>
          <span
            className={cn(
              "text-xs font-semibold px-2 py-1 rounded-full border",
              statusColors[status]
            )}
          >
            {status.charAt(0).toUpperCase() + status.slice(1)}
          </span>
        </div>

        {/* Owner Name */}
        <p className="text-neutral-600 text-sm">
          Owner: <span className="font-semibold">{ownerName}</span>
        </p>

        {/* Parcel ID in monospace font */}
        <p className="text-neutral-500 text-xs">
          Parcel ID:{' '}
          <code className="font-mono text-neutral-700 bg-neutral-100 px-1.5 py-0.5 rounded text-[0.7rem] border border-neutral-200">
            {parcelId}
          </code>
        </p>
      </div>

      {/* Favorite/Bookmark Button */}
      <button
        onClick={handleFavoriteClick}
        className={cn(
          "absolute top-3 right-3 p-2 rounded-full",
          "bg-white/90 backdrop-blur-sm shadow-sm",
          "hover:scale-110 active:scale-95 transition-transform duration-150",
          "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#0ABAB5] focus-visible:ring-offset-2"
        )}
        aria-label={isFavorite ? 'Remove from favorites' : 'Add to favorites'}
        aria-pressed={isFavorite}
      >
        <Heart
          size={18}
          className={cn(
            "transition-colors duration-150",
            isFavorite ? 'fill-red-500 text-red-500' : 'text-neutral-400 hover:text-neutral-600'
          )}
        />
      </button>
    </div>
  );
};

export default PropertyCard;
