"""
Schema Architect Agent
Purpose: Design and deploy complete database schemas for Florida data automation
Technology: OpenAI GPT-4 + Supabase SDK + Chain-of-Thought reasoning
"""

import os
import sys
from supabase import create_client
from openai import OpenAI
import json
from datetime import datetime
from dotenv import load_dotenv

# Fix encoding for Windows
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

load_dotenv(override=False)

# Initialize services
supabase = create_client(
    os.getenv("SUPABASE_URL"),
    os.getenv("SUPABASE_SERVICE_ROLE_KEY")
)
openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))


class SchemaArchitectAgent:
    """
    Chain-of-Thought Agent for Database Schema Design

    Reasoning Process:
    1. Analyze current florida_parcels structure
    2. Study 2025 NAL/SDF/NAP Users Guide specifications
    3. Design normalized schemas (stg_*, core, gis)
    4. Generate optimized indexes
    5. Create materialized views for common queries
    6. Deploy and verify
    """

    def __init__(self):
        self.name = "SchemaArchitect"
        self.version = "1.0.0"
        self.memory = []

    def think(self, context: str) -> dict:
        """Chain-of-thought reasoning using GPT-4"""
        prompt = f"""
        You are the Schema Architect Agent for Florida property data automation.

        Context: {context}

        Use chain-of-thought reasoning to:
        1. Analyze the current database structure
        2. Identify gaps vs. DOR specifications
        3. Design optimal schema organization
        4. Consider query patterns and performance
        5. Generate SQL migration script

        Respond in JSON format with:
        {{
            "reasoning": ["step 1 thought", "step 2 thought", ...],
            "design_decisions": {{}},
            "sql_migration": "..."
        }}
        """

        response = openai_client.chat.completions.create(
            model="gpt-4",
            messages=[
                {"role": "system", "content": "You are an expert database architect specializing in PostgreSQL and large-scale data systems."},
                {"role": "user", "content": prompt}
            ],
            response_format={"type": "json_object"}
        )

        result = json.loads(response.choices[0].message.content)
        self.memory.append({
            "timestamp": datetime.now().isoformat(),
            "context": context,
            "reasoning": result.get("reasoning", []),
            "output": result
        })

        return result

    def generate_complete_schema(self) -> str:
        """Generate complete schema migration SQL"""

        print(f"🏗️ {self.name} Agent: Starting schema generation...")
        print("="*80)

        # Step 1: Analyze current structure
        print("\n📊 Step 1: Analyzing current florida_parcels table...")
        analysis_result = self.think("""
        Analyze the existing florida_parcels table structure.
        It currently has columns like: parcel_id, county, year, owner_name, owner_addr1,
        phy_addr1, just_value, taxable_value, land_value, building_value, etc.

        We need to:
        1. Create separate staging schemas (stg_nal, stg_sdf, stg_nap)
        2. Design normalized core schema
        3. Add GIS schema for parcel geometry
        4. Ensure all DOR 2025 Users Guide fields are included
        """)

        print(f"   Reasoning: {analysis_result.get('reasoning', [])[:2]}")

        # Step 2: Generate complete migration
        print("\n🔨 Step 2: Generating complete migration SQL...")

        migration_sql = self._build_migration_sql()

        print(f"   ✅ Generated {len(migration_sql.split(';'))} SQL statements")

        return migration_sql

    def _build_migration_sql(self) -> str:
        """Build comprehensive migration SQL"""

        return """
-- ============================================================================
-- Florida Property Data Automation - Complete Schema Migration
-- Generated by Schema Architect Agent v1.0.0
-- Date: 2025-10-05
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================================
-- STAGING SCHEMAS
-- ============================================================================

-- Staging schema for NAL (Name, Address, Legal) data
CREATE SCHEMA IF NOT EXISTS stg_nal;

CREATE TABLE IF NOT EXISTS stg_nal.records_2025 (
    id bigserial PRIMARY KEY,

    -- Identifiers
    county_code int NOT NULL,
    parcel_id text NOT NULL,
    rs_id text, -- Roll section ID
    dor_uc text, -- DOR use code

    -- Owner information
    owner_name text,
    owner_addr1 text,
    owner_addr2 text,
    owner_city text,
    owner_state text,
    owner_zip text,
    owner_country text,

    -- Property location
    phy_addr1 text,
    phy_addr2 text,
    phy_city text,
    phy_zipcd text,

    -- Legal description
    legal_desc text,
    neighborhood text,
    subdivision text,

    -- Land characteristics
    land_sqfoot bigint,
    land_acres numeric(12,4),

    -- Values
    just_value numeric(15,2),
    assessed_value numeric(15,2),
    taxable_value numeric(15,2),
    exempt_value numeric(15,2),

    -- Breakdown
    land_value numeric(15,2),
    building_value numeric(15,2),
    xf_value numeric(15,2), -- Extra features value

    -- Metadata
    data_year int NOT NULL,
    source_file text,
    loaded_at timestamptz DEFAULT now(),

    -- Constraints
    CONSTRAINT stg_nal_unique UNIQUE (county_code, parcel_id, data_year)
);

CREATE INDEX idx_stg_nal_county ON stg_nal.records_2025(county_code);
CREATE INDEX idx_stg_nal_parcel ON stg_nal.records_2025(parcel_id);
CREATE INDEX idx_stg_nal_owner ON stg_nal.records_2025 USING gin(owner_name gin_trgm_ops);

-- Staging schema for SDF (Sales Data File)
CREATE SCHEMA IF NOT EXISTS stg_sdf;

CREATE TABLE IF NOT EXISTS stg_sdf.records_2025 (
    id bigserial PRIMARY KEY,

    -- Identifiers
    county_code int NOT NULL,
    parcel_id text NOT NULL,

    -- Sale information (up to 5 sales per parcel)
    sale_yr1 int,
    sale_mo1 int,
    sale_price1 numeric(15,2),
    sale_qual_cd1 text, -- Qualification code
    sale_inst_type1 text, -- Instrument type

    sale_yr2 int,
    sale_mo2 int,
    sale_price2 numeric(15,2),
    sale_qual_cd2 text,
    sale_inst_type2 text,

    sale_yr3 int,
    sale_mo3 int,
    sale_price3 numeric(15,2),
    sale_qual_cd3 text,
    sale_inst_type3 text,

    sale_yr4 int,
    sale_mo4 int,
    sale_price4 numeric(15,2),
    sale_qual_cd4 text,
    sale_inst_type4 text,

    sale_yr5 int,
    sale_mo5 int,
    sale_price5 numeric(15,2),
    sale_qual_cd5 text,
    sale_inst_type5 text,

    -- Metadata
    data_year int NOT NULL,
    source_file text,
    loaded_at timestamptz DEFAULT now(),

    CONSTRAINT stg_sdf_unique UNIQUE (county_code, parcel_id, data_year)
);

CREATE INDEX idx_stg_sdf_county ON stg_sdf.records_2025(county_code);
CREATE INDEX idx_stg_sdf_parcel ON stg_sdf.records_2025(parcel_id);
CREATE INDEX idx_stg_sdf_sale_date ON stg_sdf.records_2025(sale_yr1, sale_mo1);

-- Staging schema for NAP (Tangible Personal Property)
CREATE SCHEMA IF NOT EXISTS stg_nap;

CREATE TABLE IF NOT EXISTS stg_nap.records_2025 (
    id bigserial PRIMARY KEY,

    -- Identifiers
    county_code int NOT NULL,
    account_number text NOT NULL,

    -- Business information
    business_name text,
    business_addr1 text,
    business_city text,
    business_state text,
    business_zip text,

    -- Property information
    property_use text,
    sic_code text, -- Standard Industrial Classification
    naics_code text, -- North American Industry Classification

    -- Values
    assessed_value numeric(15,2),
    exempt_value numeric(15,2),

    -- Metadata
    data_year int NOT NULL,
    source_file text,
    loaded_at timestamptz DEFAULT now(),

    CONSTRAINT stg_nap_unique UNIQUE (county_code, account_number, data_year)
);

CREATE INDEX idx_stg_nap_county ON stg_nap.records_2025(county_code);
CREATE INDEX idx_stg_nap_account ON stg_nap.records_2025(account_number);
CREATE INDEX idx_stg_nap_business ON stg_nap.records_2025 USING gin(business_name gin_trgm_ops);

-- ============================================================================
-- CORE SCHEMA (Production)
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS core;

-- Core parcels table (normalized from staging)
CREATE TABLE IF NOT EXISTS core.parcels (
    id bigserial PRIMARY KEY,

    -- Identifiers
    county_code int NOT NULL,
    parcel_id text NOT NULL,
    rs_id text,
    data_year int NOT NULL,

    -- Owner
    owner_name text,
    owner_address jsonb, -- {addr1, addr2, city, state, zip, country}

    -- Property location
    property_address jsonb, -- {addr1, addr2, city, zip}
    legal_description text,
    neighborhood text,

    -- Classification
    dor_use_code text,
    property_use_description text,

    -- Measurements
    land_sqfoot bigint,
    land_acres numeric(12,4),

    -- Values
    just_value numeric(15,2),
    assessed_value numeric(15,2),
    taxable_value numeric(15,2),
    exempt_value numeric(15,2),

    -- Value breakdown
    land_value numeric(15,2),
    building_value numeric(15,2),
    extra_features_value numeric(15,2),

    -- Data quality
    data_quality_score numeric(3,2), -- 0.00 to 1.00
    validation_flags jsonb,

    -- Metadata
    source_type text DEFAULT 'DOR',
    last_validated_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),

    -- Constraints
    CONSTRAINT core_parcels_unique UNIQUE (county_code, parcel_id, data_year)
);

CREATE INDEX idx_core_parcels_county ON core.parcels(county_code);
CREATE INDEX idx_core_parcels_parcel ON core.parcels(parcel_id);
CREATE INDEX idx_core_parcels_owner ON core.parcels USING gin(owner_name gin_trgm_ops);
CREATE INDEX idx_core_parcels_dor_code ON core.parcels(dor_use_code);
CREATE INDEX idx_core_parcels_year ON core.parcels(data_year);
CREATE INDEX idx_core_parcels_value ON core.parcels(just_value) WHERE just_value IS NOT NULL;

-- Core sales history (normalized from SDF)
CREATE TABLE IF NOT EXISTS core.sales_history (
    id bigserial PRIMARY KEY,

    -- Identifiers
    county_code int NOT NULL,
    parcel_id text NOT NULL,

    -- Sale details
    sale_date date NOT NULL,
    sale_price numeric(15,2),
    sale_qualification_code text,
    sale_instrument_type text,

    -- References
    parcel_fk bigint REFERENCES core.parcels(id),

    -- Metadata
    data_year int,
    source_file text,
    created_at timestamptz DEFAULT now(),

    CONSTRAINT core_sales_unique UNIQUE (county_code, parcel_id, sale_date)
);

CREATE INDEX idx_core_sales_county ON core.sales_history(county_code);
CREATE INDEX idx_core_sales_parcel ON core.sales_history(parcel_id);
CREATE INDEX idx_core_sales_date ON core.sales_history(sale_date DESC);
CREATE INDEX idx_core_sales_price ON core.sales_history(sale_price) WHERE sale_price > 0;

-- ============================================================================
-- GIS SCHEMA (Parcel Geometry)
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS gis;

-- FGIO parcel boundaries
CREATE TABLE IF NOT EXISTS gis.parcels_geometry (
    id bigserial PRIMARY KEY,

    -- Identifiers
    county_code int NOT NULL,
    fgio_parcel_id text NOT NULL,

    -- Geometry (WGS84 - EPSG:4326)
    geom geometry(MultiPolygon, 4326),
    centroid geometry(Point, 4326),

    -- Properties
    area_sqft numeric(15,2),
    perimeter_ft numeric(15,2),

    -- Metadata
    source text DEFAULT 'FGIO',
    source_date date,
    last_updated timestamptz DEFAULT now(),

    CONSTRAINT gis_parcels_unique UNIQUE (county_code, fgio_parcel_id)
);

CREATE INDEX idx_gis_geom ON gis.parcels_geometry USING gist(geom);
CREATE INDEX idx_gis_centroid ON gis.parcels_geometry USING gist(centroid);
CREATE INDEX idx_gis_county ON gis.parcels_geometry(county_code);

-- Parcel key crosswalk (DOR parcel_id → FGIO parcel_id)
CREATE TABLE IF NOT EXISTS gis.parcel_key_xwalk (
    id bigserial PRIMARY KEY,

    county_code int NOT NULL,
    dor_parcel_id text NOT NULL,
    fgio_parcel_id text NOT NULL,

    match_confidence numeric(3,2), -- 0.00 to 1.00
    match_method text, -- 'exact', 'fuzzy', 'spatial'

    created_at timestamptz DEFAULT now(),

    CONSTRAINT xwalk_unique UNIQUE (county_code, dor_parcel_id, fgio_parcel_id)
);

CREATE INDEX idx_xwalk_dor ON gis.parcel_key_xwalk(county_code, dor_parcel_id);
CREATE INDEX idx_xwalk_fgio ON gis.parcel_key_xwalk(county_code, fgio_parcel_id);

-- ============================================================================
-- MATERIALIZED VIEWS
-- ============================================================================

-- View: Current year parcels with geometry
CREATE MATERIALIZED VIEW IF NOT EXISTS core.parcels_with_geometry AS
SELECT
    p.*,
    g.geom,
    g.centroid,
    g.area_sqft as geometry_area_sqft,
    x.match_confidence as geometry_match_confidence
FROM core.parcels p
LEFT JOIN gis.parcel_key_xwalk x
    ON p.county_code = x.county_code
    AND p.parcel_id = x.dor_parcel_id
LEFT JOIN gis.parcels_geometry g
    ON x.county_code = g.county_code
    AND x.fgio_parcel_id = g.fgio_parcel_id
WHERE p.data_year = EXTRACT(YEAR FROM CURRENT_DATE);

CREATE UNIQUE INDEX idx_parcels_geom_id ON core.parcels_with_geometry(id);
CREATE INDEX idx_parcels_geom_county ON core.parcels_with_geometry(county_code);
CREATE INDEX idx_parcels_geom_spatial ON core.parcels_with_geometry USING gist(geom);

-- View: Parcels with recent sales
CREATE MATERIALIZED VIEW IF NOT EXISTS core.parcels_with_sales AS
SELECT
    p.*,
    s.sale_date as last_sale_date,
    s.sale_price as last_sale_price,
    s.sale_qualification_code as last_sale_qual
FROM core.parcels p
LEFT JOIN LATERAL (
    SELECT * FROM core.sales_history
    WHERE county_code = p.county_code
    AND parcel_id = p.parcel_id
    ORDER BY sale_date DESC
    LIMIT 1
) s ON true
WHERE p.data_year = EXTRACT(YEAR FROM CURRENT_DATE);

CREATE UNIQUE INDEX idx_parcels_sales_id ON core.parcels_with_sales(id);
CREATE INDEX idx_parcels_sales_county ON core.parcels_with_sales(county_code);
CREATE INDEX idx_parcels_sales_date ON core.parcels_with_sales(last_sale_date DESC NULLS LAST);

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

-- Function: Refresh all materialized views
CREATE OR REPLACE FUNCTION core.refresh_all_materialized_views()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY core.parcels_with_geometry;
    REFRESH MATERIALIZED VIEW CONCURRENTLY core.parcels_with_sales;
END;
$$ LANGUAGE plpgsql;

-- Function: Get county statistics
CREATE OR REPLACE FUNCTION core.get_county_stats(p_county_code int)
RETURNS jsonb AS $$
SELECT jsonb_build_object(
    'county_code', p_county_code,
    'total_parcels', COUNT(*),
    'total_value', SUM(just_value),
    'avg_value', AVG(just_value),
    'parcels_with_sales', COUNT(*) FILTER (WHERE id IN (
        SELECT DISTINCT parcel_fk FROM core.sales_history WHERE county_code = p_county_code
    )),
    'parcels_with_geometry', COUNT(*) FILTER (WHERE id IN (
        SELECT p.id FROM core.parcels p
        JOIN gis.parcel_key_xwalk x ON p.county_code = x.county_code AND p.parcel_id = x.dor_parcel_id
        WHERE p.county_code = p_county_code
    ))
)
FROM core.parcels
WHERE county_code = p_county_code
AND data_year = EXTRACT(YEAR FROM CURRENT_DATE);
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================

-- Grant necessary permissions
GRANT USAGE ON SCHEMA stg_nal, stg_sdf, stg_nap, core, gis TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA stg_nal TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA stg_sdf TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA stg_nap TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA gis TO service_role;

-- Log migration
INSERT INTO ingestion_runs (
    run_timestamp,
    source_type,
    status,
    rows_inserted,
    rows_updated
) VALUES (
    NOW(),
    'SCHEMA_MIGRATION',
    'SUCCESS',
    0,
    0
);

-- Success message
DO $$
BEGIN
    RAISE NOTICE '✅ Schema migration completed successfully!';
    RAISE NOTICE 'Created schemas: stg_nal, stg_sdf, stg_nap, core, gis';
    RAISE NOTICE 'Created materialized views: parcels_with_geometry, parcels_with_sales';
    RAISE NOTICE 'Ready for data ingestion!';
END $$;
"""

    def deploy_schema(self, sql: str) -> dict:
        """Deploy schema to Supabase (manual step required)"""

        print("\n🚀 Step 3: Preparing deployment...")
        print("="*80)

        # Save to file for manual deployment
        output_file = "COMPLETE_SCHEMA_MIGRATION.sql"
        with open(output_file, 'w') as f:
            f.write(sql)

        print(f"\n✅ Schema SQL saved to: {output_file}")
        print("\nMANUAL DEPLOYMENT REQUIRED:")
        print("1. Go to Supabase SQL Editor")
        print("2. Open COMPLETE_SCHEMA_MIGRATION.sql")
        print("3. Copy and paste the entire content")
        print("4. Click 'Run'")
        print("5. Verify success message\n")

        return {
            "status": "ready_for_deployment",
            "file": output_file,
            "lines": len(sql.split('\n')),
            "statements": len(sql.split(';'))
        }


if __name__ == "__main__":
    print("="*80)
    print("SCHEMA ARCHITECT AGENT - AUTONOMOUS EXECUTION")
    print("="*80)

    agent = SchemaArchitectAgent()

    # Generate complete schema
    schema_sql = agent.generate_complete_schema()

    # Prepare for deployment
    result = agent.deploy_schema(schema_sql)

    print(f"\n📊 Deployment Ready:")
    print(f"   File: {result['file']}")
    print(f"   Lines: {result['lines']}")
    print(f"   Statements: {result['statements']}")
    print("\n" + "="*80)
