import type { Meta, StoryObj } from '@storybook/react';
import { MetricCard, MetricCardSkeleton } from '../../components/ui/metric-card';
import {
  Home,
  DollarSign,
  ScrollText,
  TrendingUp,
  Users,
  Building2,
  MapPin,
  FileText,
} from 'lucide-react';

const meta: Meta<typeof MetricCard> = {
  title: 'Components/MetricCard',
  component: MetricCard,
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component: 'A metric card component for displaying analytics data on dashboards. Generated by Nano Banana Design Agent.',
      },
    },
  },
  tags: ['autodocs'],
  argTypes: {
    size: {
      control: 'select',
      options: ['sm', 'md', 'lg'],
    },
    isGold: {
      control: 'boolean',
    },
    isLoading: {
      control: 'boolean',
    },
  },
};

export default meta;
type Story = StoryObj<typeof MetricCard>;

export const Default: Story = {
  args: {
    label: 'Total Properties',
    value: '9,113,150',
    icon: Home,
    comparisonValue: 2.3,
    size: 'md',
  },
  render: (args) => (
    <div className="w-64">
      <MetricCard {...args} />
    </div>
  ),
};

export const NegativeTrend: Story = {
  args: {
    label: 'Tax Certificates',
    value: '45,320',
    icon: ScrollText,
    comparisonValue: -1.2,
    size: 'md',
  },
  render: (args) => (
    <div className="w-64">
      <MetricCard {...args} />
    </div>
  ),
};

export const Currency: Story = {
  args: {
    label: 'Average Value',
    value: '$325,000',
    icon: DollarSign,
    comparisonValue: 5.1,
    size: 'md',
  },
  render: (args) => (
    <div className="w-64">
      <MetricCard {...args} />
    </div>
  ),
};

export const Premium: Story = {
  args: {
    label: 'Premium Listings',
    value: '1,234',
    icon: TrendingUp,
    comparisonValue: 12.5,
    isGold: true,
    size: 'md',
  },
  render: (args) => (
    <div className="w-64">
      <MetricCard {...args} />
    </div>
  ),
};

export const WithSparkline: Story = {
  args: {
    label: 'Active Listings',
    value: '12,456',
    icon: Building2,
    comparisonValue: 3.2,
    sparklineData: [10, 15, 12, 18, 22, 19, 25, 28, 24, 30],
    size: 'md',
  },
  render: (args) => (
    <div className="w-64">
      <MetricCard {...args} />
    </div>
  ),
};

export const PremiumWithSparkline: Story = {
  args: {
    label: 'Revenue',
    value: '$1.2M',
    icon: DollarSign,
    comparisonValue: 8.7,
    sparklineData: [20, 25, 22, 30, 35, 32, 40, 45, 42, 50],
    isGold: true,
    size: 'md',
  },
  render: (args) => (
    <div className="w-64">
      <MetricCard {...args} />
    </div>
  ),
};

export const Sizes: Story = {
  name: 'All Sizes',
  render: () => (
    <div className="flex flex-col gap-4 items-start">
      <div>
        <p className="text-sm text-neutral-500 mb-2">Small</p>
        <div className="w-48">
          <MetricCard
            label="Properties"
            value="9.1M"
            icon={Home}
            comparisonValue={2.3}
            size="sm"
          />
        </div>
      </div>
      <div>
        <p className="text-sm text-neutral-500 mb-2">Medium (default)</p>
        <div className="w-64">
          <MetricCard
            label="Total Properties"
            value="9,113,150"
            icon={Home}
            comparisonValue={2.3}
            size="md"
          />
        </div>
      </div>
      <div>
        <p className="text-sm text-neutral-500 mb-2">Large</p>
        <div className="w-80">
          <MetricCard
            label="Total Properties"
            value="9,113,150"
            icon={Home}
            comparisonValue={2.3}
            size="lg"
          />
        </div>
      </div>
    </div>
  ),
};

export const Loading: Story = {
  name: 'Loading Skeleton',
  render: () => (
    <div className="flex gap-4">
      <div className="w-48">
        <MetricCardSkeleton size="sm" />
      </div>
      <div className="w-64">
        <MetricCardSkeleton size="md" />
      </div>
      <div className="w-80">
        <MetricCardSkeleton size="lg" />
      </div>
    </div>
  ),
};

export const Clickable: Story = {
  args: {
    label: 'Active Listings',
    value: '12,456',
    icon: Building2,
    comparisonValue: 3.2,
    size: 'md',
    onClick: () => alert('Card clicked!'),
  },
  render: (args) => (
    <div className="w-64">
      <MetricCard {...args} />
    </div>
  ),
};

export const DashboardGrid: Story = {
  name: 'Dashboard Layout',
  render: () => (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 p-4 max-w-4xl">
      <MetricCard
        label="Total Properties"
        value="9,113,150"
        icon={Home}
        comparisonValue={2.3}
      />
      <MetricCard
        label="Average Value"
        value="$325,000"
        icon={DollarSign}
        comparisonValue={5.1}
        isGold
      />
      <MetricCard
        label="Tax Certificates"
        value="45,320"
        icon={ScrollText}
        comparisonValue={-1.2}
      />
      <MetricCard
        label="Active Listings"
        value="12,456"
        icon={Building2}
        comparisonValue={3.2}
      />
      <MetricCard
        label="Florida Counties"
        value="67"
        icon={MapPin}
        comparisonValue={0}
      />
      <MetricCard
        label="Property Owners"
        value="6.8M"
        icon={Users}
        comparisonValue={1.8}
      />
      <MetricCard
        label="Documents"
        value="2.5M"
        icon={FileText}
        comparisonValue={4.2}
        sparklineData={[5, 8, 12, 10, 15, 18, 22, 20, 25]}
      />
      <MetricCard
        label="Monthly Revenue"
        value="$1.2M"
        icon={TrendingUp}
        comparisonValue={12.5}
        isGold
        sparklineData={[20, 25, 30, 28, 35, 40, 45, 42, 50]}
      />
    </div>
  ),
};
