import type { Meta, StoryObj } from '@storybook/react';
import { PropertyCard, PropertyCardSkeleton } from '../../components/ui/property-card';
import { useState } from 'react';

const meta: Meta<typeof PropertyCard> = {
  title: 'Components/PropertyCard',
  component: PropertyCard,
  parameters: {
    layout: 'centered',
    docs: {
      description: {
        component: 'A property card component displaying key property information with modern styling. Generated by Nano Banana Design Agent.',
      },
    },
  },
  tags: ['autodocs'],
  argTypes: {
    propertyType: {
      control: 'select',
      options: ['residential', 'commercial', 'vacant land'],
    },
    status: {
      control: 'select',
      options: ['active', 'pending', 'sold'],
    },
    isPremium: {
      control: 'boolean',
    },
    isLoading: {
      control: 'boolean',
    },
  },
};

export default meta;
type Story = StoryObj<typeof PropertyCard>;

// Interactive story with state management
const PropertyCardWithState = (args: any) => {
  const [isFavorite, setIsFavorite] = useState(args.isFavorite);

  return (
    <div className="w-80">
      <PropertyCard
        {...args}
        isFavorite={isFavorite}
        onClick={(id) => console.log('Card clicked:', id)}
        onToggleFavorite={(id, newState) => {
          console.log('Toggle favorite:', id, newState);
          setIsFavorite(newState);
        }}
      />
    </div>
  );
};

export const Default: Story = {
  render: (args) => <PropertyCardWithState {...args} />,
  args: {
    parcelId: '484330110110',
    streetAddress: '123 Ocean Drive',
    city: 'Fort Lauderdale',
    state: 'FL',
    zipCode: '33301',
    justValue: 485000,
    ownerName: 'SMITH JOHN & MARY',
    propertyType: 'residential',
    status: 'active',
    isFavorite: false,
    isPremium: false,
    isLoading: false,
  },
};

export const Premium: Story = {
  render: (args) => <PropertyCardWithState {...args} />,
  args: {
    ...Default.args,
    streetAddress: '1 Billionaire Boulevard',
    city: 'Palm Beach',
    justValue: 8500000,
    ownerName: 'LUXURY ESTATES LLC',
    isPremium: true,
    isFavorite: true,
  },
};

export const Commercial: Story = {
  render: (args) => <PropertyCardWithState {...args} />,
  args: {
    ...Default.args,
    parcelId: '504212050001',
    streetAddress: '500 Downtown Plaza',
    city: 'Miami',
    zipCode: '33131',
    justValue: 2250000,
    ownerName: 'DOWNTOWN PROPERTIES INC',
    propertyType: 'commercial',
    status: 'active',
  },
};

export const VacantLand: Story = {
  render: (args) => <PropertyCardWithState {...args} />,
  args: {
    ...Default.args,
    parcelId: '123456789012',
    streetAddress: 'Lot 42 Sunrise Heights',
    city: 'Ocala',
    zipCode: '34470',
    justValue: 75000,
    ownerName: 'LAND INVESTORS GROUP',
    propertyType: 'vacant land',
    status: 'pending',
  },
};

export const SoldProperty: Story = {
  render: (args) => <PropertyCardWithState {...args} />,
  args: {
    ...Default.args,
    parcelId: '987654321098',
    streetAddress: '789 Sold Lane',
    city: 'Tampa',
    zipCode: '33602',
    justValue: 320000,
    ownerName: 'PREVIOUS OWNER LLC',
    status: 'sold',
    imageUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&q=80',
  },
};

export const WithImage: Story = {
  render: (args) => <PropertyCardWithState {...args} />,
  args: {
    ...Default.args,
    imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80',
    justValue: 625000,
  },
};

export const Favorited: Story = {
  render: (args) => <PropertyCardWithState {...args} />,
  args: {
    ...Default.args,
    isFavorite: true,
  },
};

export const Loading: Story = {
  name: 'Loading Skeleton',
  render: () => (
    <div className="w-80">
      <PropertyCardSkeleton />
    </div>
  ),
};

export const CardGrid: Story = {
  name: 'Grid Layout',
  render: () => {
    const [favorites, setFavorites] = useState<Record<string, boolean>>({});

    const properties = [
      {
        parcelId: '001',
        streetAddress: '123 Ocean Drive',
        city: 'Fort Lauderdale',
        state: 'FL',
        zipCode: '33301',
        justValue: 485000,
        ownerName: 'SMITH JOHN',
        propertyType: 'residential' as const,
        status: 'active' as const,
        isPremium: false,
      },
      {
        parcelId: '002',
        streetAddress: '1 Billionaire Blvd',
        city: 'Palm Beach',
        state: 'FL',
        zipCode: '33480',
        justValue: 8500000,
        ownerName: 'LUXURY ESTATES LLC',
        propertyType: 'residential' as const,
        status: 'active' as const,
        isPremium: true,
        imageUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&q=80',
      },
      {
        parcelId: '003',
        streetAddress: '500 Downtown Plaza',
        city: 'Miami',
        state: 'FL',
        zipCode: '33131',
        justValue: 2250000,
        ownerName: 'DOWNTOWN PROPS INC',
        propertyType: 'commercial' as const,
        status: 'pending' as const,
        isPremium: false,
      },
      {
        parcelId: '004',
        streetAddress: 'Lot 42 Sunrise Heights',
        city: 'Ocala',
        state: 'FL',
        zipCode: '34470',
        justValue: 75000,
        ownerName: 'LAND INVESTORS',
        propertyType: 'vacant land' as const,
        status: 'active' as const,
        isPremium: false,
      },
    ];

    return (
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 p-4">
        {properties.map((property) => (
          <PropertyCard
            key={property.parcelId}
            {...property}
            isFavorite={favorites[property.parcelId] || false}
            onClick={(id) => console.log('Clicked:', id)}
            onToggleFavorite={(id, state) => {
              setFavorites(prev => ({ ...prev, [id]: state }));
            }}
          />
        ))}
      </div>
    );
  },
};
