-- Broward County DOR Use Type Codes
-- Scraped from https://bcpa.net/UseType.asp
-- Total codes: 626

INSERT INTO dor_use_codes_std (main_code, sub_code, full_code, description, category) VALUES
('00', '01', '00-01', 'Vacant Residential', 'Vacant Land'),
('00', '02', '00-02', 'Vacant Residential Land - Condominium', 'Vacant Land'),
('00', '03', '00-03', 'Vacant Residential Common Area', 'Vacant Land'),
('00', '04', '00-04', 'Vacant Residential with extra feature', 'Vacant Land'),
('01', '01', '01-01', 'Single Family', 'Residential'),
('01', '02', '01-02', 'House w/guest house', 'Residential'),
('01', '03', '01-03', '(Extra Features Only) - Miscellaneous (Barn, Extra features)', 'Residential'),
('01', '04', '01-04', 'Townhome', 'Residential'),
('01', '05', '01-05', 'Single Family Zero Lot Line', 'Residential'),
('01', '06', '01-06', 'Attached 1-story', 'Residential'),
('01', '07', '01-07', 'Single Family - Group Home/ALF', 'Residential'),
('02', '01', '02-01', 'Manufactured/Modular Housing - Single', 'Residential'),
('02', '02', '02-02', 'Manufactured/Modular Housing - Double', 'Residential'),
('02', '03', '02-03', 'Manufactured/Modular Housing - Triple', 'Residential'),
('02', '04', '02-04', 'Manufactured/Modular Housing - Site Improvements Only', 'Residential'),
('02', '99', '02-99', 'Manufactured/Modular Housing not suitable for occupancy / Redevelopment', 'Residential'),
('03', '01', '03-01', 'Multi-family 10 to 49 units', 'Residential'),
('03', '02', '03-02', 'Multi-family 50 to 99 units', 'Residential'),
('03', '03', '03-03', 'Multi-family 100 units +', 'Residential'),
('03', '04', '03-04', 'Multi-family - Low Income Housing Tax Credit', 'Residential'),
('03', '05', '03-05', 'Low end housing (multiple parcels operating as one income producing property)', 'Residential'),
('03', '99', '03-99', 'Multi-family not suitable for occupancy / Redevelopment', 'Residential'),
('04', '01', '04-01', 'Condominium - Residential', 'Residential'),
('04', '02', '04-02', 'Condominium - Residential Single Family Home / Zero Lot', 'Residential'),
('04', '03', '04-03', 'Condominium - Manufactured Home', 'Residential'),
('04', '04', '04-04', 'Condominium - Timeshare / Interval Ownership', 'Residential'),
('04', '05', '04-05', 'Condominium - Limited Common Area', 'Residential'),
('04', '06', '04-06', 'Condominium - Association owned Common Area', 'Residential'),
('04', '28', '04-28', 'Condominium - Parking Space', 'Residential'),
('04', '99', '04-99', 'Condominium not suitable for occupancy / Redevelopment', 'Residential'),
('05', '01', '05-01', 'Cooperatives - Residential', 'Residential'),
('05', '02', '05-02', 'Cooperatives - Residential Single Family Home', 'Residential'),
('05', '03', '05-03', 'Cooperatives - Manufactured House - Single', 'Residential'),
('05', '04', '05-04', 'Cooperatives - Manufactured House - Double', 'Residential'),
('05', '05', '05-05', 'Cooperatives - Manufactured House - Triple', 'Residential'),
('05', '06', '05-06', 'Cooperatives - Manufactured Home', 'Residential'),
('05', '07', '05-07', 'Cooperatives - Limited Common Area', 'Residential'),
('05', '08', '05-08', 'Cooperatives - Association owned Common Area', 'Residential'),
('05', '99', '05-99', 'Cooperatives not suitable for occupancy / Redevelopment', 'Residential'),
('06', '01', '06-01', 'Retirement homes (not eligible for exemption under section)', 'Residential'),
('06', '99', '06-99', 'Retirement home facility not suitable for occupancy / Redevelopment', 'Residential'),
('07', '01', '07-01', 'Miscellaneous residential (migrant camp, boarding homes, etc,)', 'Residential'),
('07', '02', '07-02', 'Mics. value on separate folio (pool, cabanas, rec. bldgs. Tennis courts, etc.)', 'Residential'),
('07', '03', '07-03', 'Miscellaneous residential air rights', 'Residential'),
('07', '99', '07-99', 'Miscellaneous residential not suitable for occupancy / Redevelopment', 'Residential'),
('08', '01', '08-01', 'Duplex with Guest House', 'Residential'),
('08', '02', '08-02', 'Multi-family 2 units - Duplex', 'Residential'),
('08', '03', '08-03', 'Multi-family 3 units -Triplex', 'Residential'),
('08', '04', '08-04', 'Multi-family 4 units - Quadplex', 'Residential'),
('08', '05', '08-05', 'Multi-family 5 - 9 units', 'Residential'),
('08', '06', '08-06', 'Single Family House with 2 or more rental units', 'Residential'),
('08', '07', '08-07', 'Three or more Single Family Homes with 3 or more rental units', 'Residential'),
('08', '08', '08-08', 'Two or more Townhouses', 'Residential'),
('08', '09', '08-09', 'Two or more Manufactured Homes (not a park)', 'Residential'),
('08', '10', '08-10', 'Transitional Housing', 'Residential'),
('08', '11', '08-11', 'Low end housing (multiple parcels operating as one income producing property)', 'Residential'),
('08', '99', '08-99', 'Multi-family improvements not suitable for occupancy / Redevelopment', 'Residential'),
('09', '00', '09-00', 'Undefined - reserved for use by Department of Revenue only', 'Residential'),
('09', '01', '09-01', 'Miscellaneous residential (migrant camp, boarding homes, etc,)', 'Residential'),
('09', '02', '09-02', 'Mics. value on separate folio (pool, cabanas, rec. bldgs. Tennis courts, etc.)', 'Residential'),
('09', '03', '09-03', 'Miscellaneous residential air rights', 'Residential'),
('09', '28', '09-28', 'Miscellaneous residential parking garage', 'Residential'),
('09', '99', '09-99', 'Miscellaneous residential not suitable for occupancy / Redevelopment', 'Residential'),
('10', '01', '10-01', 'Vacant Commercial', 'Commercial'),
('10', '02', '10-02', 'Vacant Commercial with extra feature', 'Commercial'),
('10', '03', '10-03', 'Vacant Commercial Common Area', 'Commercial'),
('10', '04', '10-04', 'Vacant Commercial Land - Condominium', 'Commercial'),
('10', '05', '10-05', 'Vacant Land Under High Tension Wires Not Utility Owned', 'Commercial'),
('10', '06', '10-06', 'Vacant Land Under High Tension Wires Utility Owned', 'Commercial'),
('10', '99', '10-99', 'Vacant Commercial not suitable for occupancy / Redevelopment', 'Commercial'),
('11', '01', '11-01', 'Retail Store - 1 unit', 'Commercial'),
('11', '02', '11-02', 'Retail up to 4,999 sq. ft.', 'Commercial'),
('11', '03', '11-03', 'Retail - 5,000 sq. ft. to 20,000 sq. ft.', 'Commercial'),
('11', '04', '11-04', 'Condominium - Commercial Retail', 'Commercial'),
('11', '05', '11-05', 'Retail greater than 20,000 sq. ft.', 'Commercial'),
('11', '06', '11-06', 'Drug Store - free standing, not attached', 'Commercial'),
('11', '07', '11-07', 'Discount Store (Brands mart, Best Buy, etc.)', 'Commercial'),
('11', '08', '11-08', 'Warehouse Discount Store (Costco, BJ''s, Sam''s Club, etc.)', 'Commercial'),
('11', '09', '11-09', 'Home Improvement Center (Home Depot, Lowe''s etc.)', 'Commercial'),
('11', '10', '11-10', 'Convenience Store', 'Commercial'),
('11', '11', '11-11', 'Convenience Store with gas pumps', 'Commercial'),
('11', '12', '11-12', 'Convenience Store with drive-thru', 'Commercial'),
('11', '13', '11-13', 'Flea Market / Swap Meet', 'Commercial'),
('11', '14', '11-14', 'Retail - prior residence', 'Commercial'),
('11', '15', '11-15', 'Fitness Center', 'Commercial'),
('11', '16', '11-16', 'Retail Food Hall / Cafeteria / Food Kiosk', 'Commercial'),
('11', '17', '11-17', 'Medical Dispensary (single tenant only)', 'Commercial'),
('11', '99', '11-99', 'Retail improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('12', '01', '12-01', 'Mixed store or office and residential', 'Commercial'),
('12', '02', '12-02', 'Mixed store and office', 'Commercial'),
('12', '03', '12-03', 'Mixed store and warehouse', 'Commercial'),
('12', '04', '12-04', 'Miscellaneous mixed uses not included in other codes', 'Commercial'),
('12', '05', '12-05', 'Office and Restaurant', 'Commercial'),
('12', '06', '12-06', 'Apartment with Ground Floor Retail (multiple tenants on ground floor)', 'Commercial'),
('12', '99', '12-99', 'Mixed use improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('13', '01', '13-01', 'Department Stores (Macy''s, Sears, J.C. Penny, etc.)', 'Commercial'),
('13', '02', '13-02', 'Discount Department Stores (Wal-Mart, Kmart, Target, etc.) *', 'Commercial'),
('13', '03', '13-03', 'Super Discount Department Stores w/grocery (Wal-Mart, Kmart, Target, etc.)', 'Commercial'),
('13', '99', '13-99', 'Department Stores not suitable for occupancy / Redevelopment', 'Commercial'),
('14', '01', '14-01', 'Supermarkets', 'Commercial'),
('14', '02', '14-02', 'Supermarkets (not chain)', 'Commercial'),
('14', '99', '14-99', 'Supermarkets not suitable for occupancy / Redevelopment', 'Commercial'),
('15', '01', '15-01', 'Regional Shopping Center', 'Commercial'),
('15', '99', '15-99', 'Regional Shopping Center not suitable for occupancy / Redevelopment', 'Commercial'),
('16', '01', '16-01', 'Shopping Center - Community', 'Commercial'),
('16', '02', '16-02', 'Shopping Center - Neighborhood', 'Commercial'),
('16', '99', '16-99', 'Shopping Center not suitable for occupancy / Redevelopment', 'Commercial'),
('17', '01', '17-01', 'Office building - non professional, 1 story', 'Commercial'),
('17', '02', '17-02', 'Office - modular building, 1 story', 'Commercial'),
('17', '03', '17-03', 'Office building / warehouse, 1 story', 'Commercial'),
('17', '04', '17-04', 'Condominium Office, 1 story', 'Commercial'),
('17', '05', '17-05', 'Office building / retail, 1 story', 'Commercial'),
('17', '06', '17-06', 'Office building - prior residence', 'Commercial'),
('17', '07', '17-07', 'Office Complex, 1 story', 'Commercial'),
('17', '08', '17-08', 'Post Office - Non Exempt', 'Commercial'),
('17', '99', '17-99', 'Office improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('18', '01', '18-01', 'Office building, single tenant - 2 or more stories', 'Commercial'),
('18', '02', '18-02', 'Office building, multi tenant - 2 or more stories', 'Commercial'),
('18', '03', '18-03', 'Office building, multi story / tenant with bank on 1st floor', 'Commercial'),
('18', '04', '18-04', 'Condominium Office, multi story', 'Commercial'),
('18', '05', '18-05', 'Office building, multi story / tenant with retail on 1st floor', 'Commercial'),
('18', '06', '18-06', 'Office building - multi story - prior residence', 'Commercial'),
('18', '07', '18-07', 'Office building, multi story with warehouse', 'Commercial'),
('18', '08', '18-08', 'Office Complex, multi story', 'Commercial'),
('18', '99', '18-99', 'Office improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('19', '01', '19-01', 'Professional building - single tenant, 1 story', 'Commercial'),
('19', '02', '19-02', 'Professional building - multi tenant, 1 story', 'Commercial'),
('19', '03', '19-03', 'Professional building - single tenant, 2 or more stories', 'Commercial'),
('19', '04', '19-04', 'Condominium Professional building', 'Commercial'),
('19', '05', '19-05', 'Professional building - multi tenant, 2 or more stories', 'Commercial'),
('19', '06', '19-06', 'Professional building - prior residence', 'Commercial'),
('19', '07', '19-07', 'Professional office complex', 'Commercial'),
('19', '08', '19-08', 'Day Care Center / Facility', 'Commercial'),
('19', '09', '19-09', 'Day Care Center / Facility - prior residence', 'Commercial'),
('19', '10', '19-10', 'Medical - Doctor / Dentist office', 'Commercial'),
('19', '11', '19-11', 'Medical - Doctor / Dentist office - prior residence', 'Commercial'),
('19', '12', '19-12', 'Veterinarian Office', 'Commercial'),
('19', '13', '19-13', 'Veterinarian Office - prior residence', 'Commercial'),
('19', '14', '19-14', 'Animal Hospital', 'Commercial'),
('19', '15', '19-15', 'Animal Kennel', 'Commercial'),
('19', '16', '19-16', 'Animal Hospital / Kennel - prior residence', 'Commercial'),
('19', '17', '19-17', 'Radio or TV station', 'Commercial'),
('19', '99', '19-99', 'Professional improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('20', '01', '20-01', 'Airports - Private', 'Commercial'),
('20', '02', '20-02', 'Airports - Commercial', 'Commercial'),
('20', '03', '20-03', 'Bus Terminals', 'Commercial'),
('20', '04', '20-04', 'Condominium Marinas', 'Commercial'),
('20', '05', '20-05', 'Condominium Boat Docks / Slips', 'Commercial'),
('20', '06', '20-06', 'Dry Boat Storage', 'Commercial'),
('20', '07', '20-07', 'Marina - repair facilities', 'Commercial'),
('20', '08', '20-08', 'Marina - boat manufacturing', 'Commercial'),
('20', '09', '20-09', 'Marina - mixed use (retail store/restaurants/docks)', 'Commercial'),
('20', '10', '20-10', 'Marina - Yacht Club', 'Commercial'),
('20', '11', '20-11', 'Marina - slips / rack storage', 'Commercial'),
('20', '12', '20-12', 'Marina - slips / ground storage', 'Commercial'),
('20', '13', '20-13', 'Marina - slips / boat sales', 'Commercial'),
('20', '14', '20-14', 'Piers - Fishing', 'Commercial'),
('20', '15', '20-15', 'Deeded Boat Slip', 'Commercial'),
('20', '16', '20-16', 'Marina - extra features only/no bldg square footage', 'Commercial'),
('20', '99', '20-99', 'Improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('21', '01', '21-01', 'Restaurants - non franchise', 'Commercial'),
('21', '02', '21-02', 'Restaurants - franchise sit down (Olive Garden, Bennigans, Red Lobster, etc.)', 'Commercial'),
('21', '03', '21-03', 'Restaurants - carryout / delivery only', 'Commercial'),
('21', '04', '21-04', 'Restaurants - prior residence', 'Commercial'),
('21', '05', '21-05', 'Cafeteria/Food Hall', 'Commercial'),
('21', '06', '21-06', 'Restaurants - Converted Warehouse', 'Commercial'),
('21', '07', '21-07', 'Restaurants – Converted shipping container', 'Commercial'),
('21', '08', '21-08', 'Restaurants/Entertainment - TopGolf', 'Commercial'),
('21', '99', '21-99', 'Restaurant improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('22', '01', '22-01', 'Restaurants - Fast Food, franchise', 'Commercial'),
('22', '02', '22-02', 'Restaurants - Fast Food, non-franchise', 'Commercial'),
('22', '03', '22-03', 'Restaurants, Drive in only', 'Commercial'),
('22', '99', '22-99', 'Fast Food / Drive-in restaurant improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('23', '01', '23-01', 'Financial Institution', 'Commercial'),
('23', '02', '23-02', 'Financial Institution - Branch Facility', 'Commercial'),
('23', '03', '23-03', 'Financial Institution - Drive-In only', 'Commercial'),
('23', '04', '23-04', 'Financial Institution - prior residence', 'Commercial'),
('23', '99', '23-99', 'Financial Institution improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('24', '01', '24-01', 'Insurance company offices, single or multi story', 'Commercial'),
('24', '02', '24-02', 'Insurance company offices, single or multi story - prior residence', 'Commercial'),
('24', '99', '24-99', 'Insurance company office improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('25', '01', '25-01', 'Repair service shops (excluding automotive)', 'Commercial'),
('25', '02', '25-02', 'Commercial Laundry / Dry Cleaner (not coin laundry)', 'Commercial'),
('25', '03', '25-03', 'Laundromat / coin laundry', 'Commercial'),
('25', '99', '25-99', 'Repair / Laundry improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('26', '01', '26-01', 'Service Station (with Auto Repair)', 'Commercial'),
('26', '02', '26-02', 'Service Station (with small convenience store)', 'Commercial'),
('26', '03', '26-03', 'Service Station (with tenant - Subway, Pizza Hut, etc.)', 'Commercial'),
('26', '04', '26-04', 'Truck Stop', 'Commercial'),
('26', '99', '26-99', 'Service facility / Truck Stop improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('27', '01', '27-01', 'Auto Dealership Sales / full service center', 'Commercial'),
('27', '02', '27-02', 'Auto Dealership Sales / full service center with parking garage', 'Commercial'),
('27', '03', '27-03', 'Used automobile sales, independent', 'Commercial'),
('27', '04', '27-04', 'Garage / auto body / auto paint shop', 'Commercial'),
('27', '05', '27-05', 'Truck sales / service', 'Commercial'),
('27', '06', '27-06', 'Manufactured home sales', 'Commercial'),
('27', '07', '27-07', 'RV sales / service', 'Commercial'),
('27', '08', '27-08', 'Carwash (full service)', 'Commercial'),
('27', '09', '27-09', 'Carwash ( self-service)', 'Commercial'),
('27', '10', '27-10', 'Quick Lube facility', 'Commercial'),
('27', '11', '27-11', 'Tire dealer sales / repair', 'Commercial'),
('27', '12', '27-12', 'Farm and machinery sales / service', 'Commercial'),
('27', '13', '27-13', 'Auto rental / leasing facilities', 'Commercial'),
('27', '99', '27-99', 'Auto / Marine facility improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('28', '01', '28-01', 'Parking lot', 'Commercial'),
('28', '02', '28-02', 'Parking garage', 'Commercial'),
('28', '03', '28-03', 'Manufactured Home park', 'Commercial'),
('28', '04', '28-04', 'RV park', 'Commercial'),
('28', '05', '28-05', 'Individually Owned MHP', 'Commercial'),
('28', '99', '28-99', 'Use code 28 improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('29', '01', '29-01', 'Wholesale outlets', 'Commercial'),
('29', '02', '29-02', 'Produce house', 'Commercial'),
('29', '03', '29-03', 'Manufacturing outlets', 'Commercial'),
('29', '99', '29-99', 'Use code 29 improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('30', '01', '30-01', 'Florist', 'Commercial'),
('30', '02', '30-02', 'Greenhouse', 'Commercial'),
('30', '03', '30-03', 'Nursery (non-agricultural classification)', 'Commercial'),
('30', '99', '30-99', 'Use code 30 improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('31', '01', '31-01', 'Theatre (drive-in)', 'Commercial'),
('31', '02', '31-02', 'Stadium (not enclosed)', 'Commercial'),
('31', '99', '31-99', 'Theatre / Stadium improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('32', '01', '32-01', 'Theatre (enclosed)', 'Commercial'),
('32', '02', '32-02', 'Auditorium (enclosed)', 'Commercial'),
('32', '99', '32-99', 'Theatre / Auditorium improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('33', '01', '33-01', 'Nightclubs', 'Commercial'),
('33', '02', '33-02', 'Bars', 'Commercial'),
('33', '03', '33-03', 'Yacht Clubs', 'Commercial'),
('33', '04', '33-04', 'Tennis clubs', 'Commercial'),
('33', '05', '33-05', 'Clubhouses', 'Commercial'),
('33', '06', '33-06', 'Social clubs', 'Commercial'),
('33', '99', '33-99', 'Use code 33 improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('34', '01', '34-01', 'Bowling alleys', 'Commercial'),
('34', '02', '34-02', 'Skating rinks', 'Commercial'),
('34', '03', '34-03', 'Pool / Billiard halls', 'Commercial'),
('34', '04', '34-04', 'Enclosed arenas', 'Commercial'),
('34', '05', '34-05', 'Enclosed Entertainment (Indoor - arcade, skating rink, pool hall, bowling alley, etc.)', 'Commercial'),
('34', '99', '34-99', 'Use code 34 improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('35', '01', '35-01', 'Tourist attractions', 'Commercial'),
('35', '02', '35-02', 'Permanent exhibits', 'Commercial'),
('35', '03', '35-03', 'Entertainment facilities (mini golf, go-carts, etc.)', 'Commercial'),
('35', '04', '35-04', 'Amusement parks', 'Commercial'),
('35', '05', '35-05', 'Fairgrounds (privately owned)', 'Commercial'),
('35', '99', '35-99', 'Use code 35 improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('36', '01', '36-01', 'Camps', 'Commercial'),
('36', '99', '36-99', 'Camp improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('37', '01', '37-01', 'Race track - horse with casino', 'Commercial'),
('37', '02', '37-02', 'Race track - dog with casino', 'Commercial'),
('37', '03', '37-03', 'Race track - auto', 'Commercial'),
('37', '04', '37-04', 'Jai-Alai Fronton', 'Commercial'),
('37', '05', '37-05', 'Casino', 'Commercial'),
('37', '99', '37-99', 'Use code 37 improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('38', '01', '38-01', 'Golf Course - Public, privately owned', 'Commercial'),
('38', '02', '38-02', 'Golf Course - Private', 'Commercial'),
('38', '03', '38-03', 'Golf Course - Municipal', 'Commercial'),
('38', '04', '38-04', 'Golf Course - Executive', 'Commercial'),
('38', '05', '38-05', 'Golf Course - Par Three', 'Commercial'),
('38', '06', '38-06', 'Golf Driving Range', 'Commercial'),
('38', '07', '38-07', 'Golf Course - Maint Shed / Whse', 'Commercial'),
('38', '99', '38-99', 'Golf Course / Driving Range improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('39', '01', '39-01', 'Hotel - limited service with food', 'Commercial'),
('39', '02', '39-02', 'Hotel - limited service without food', 'Commercial'),
('39', '03', '39-03', 'Hotel - full service', 'Commercial'),
('39', '04', '39-04', 'Hotel - suite / extended stay', 'Commercial'),
('39', '05', '39-05', 'Condominium - hotel / motel', 'Commercial'),
('39', '06', '39-06', 'Hotel - luxury resort', 'Commercial'),
('39', '07', '39-07', 'Hotel - convention center, resort', 'Commercial'),
('39', '08', '39-08', 'Motel - no restaurant', 'Commercial'),
('39', '09', '39-09', 'Motel - with restaurant', 'Commercial'),
('39', '10', '39-10', 'Bed and Breakfast', 'Commercial'),
('39', '99', '39-99', 'Hotel / Motel improvements not suitable for occupancy / Redevelopment', 'Commercial'),
('40', '01', '40-01', 'Vacant Industrial', 'Industrial'),
('40', '02', '40-02', 'Vacant Industrial with extra features', 'Industrial'),
('40', '03', '40-03', 'Vacant Industrial Common Area', 'Industrial'),
('40', '04', '40-04', 'Vacant Industrial Land - Condominium', 'Industrial'),
('40', '99', '40-99', 'Vacant Industrial not suitable for occupancy / Redevelopment', 'Industrial'),
('41', '01', '41-01', 'Light Manufacturing', 'Industrial'),
('41', '02', '41-02', 'Small Equipment Manufacturing', 'Industrial'),
('41', '03', '41-03', 'Small Machine Shops', 'Industrial'),
('41', '04', '41-04', 'Instrument Manufacturing', 'Industrial'),
('41', '05', '41-05', 'Printing Plants', 'Industrial'),
('41', '06', '41-06', 'Miscellaneous Industrial Facility', 'Industrial'),
('41', '99', '41-99', 'Manufacturing improvements not suitable for occupancy / Redevelopment', 'Industrial'),
('42', '01', '42-01', 'Heavy Industrial', 'Industrial'),
('42', '02', '42-02', 'Heavy Equipment Manufacturing', 'Industrial'),
('42', '03', '42-03', 'Large Machine Shops', 'Industrial'),
('42', '04', '42-04', 'Foundries', 'Industrial'),
('42', '05', '42-05', 'Steel Fabricating Plants', 'Industrial'),
('42', '06', '42-06', 'Auto or Aircraft Plants', 'Industrial'),
('42', '99', '42-99', 'Heavy Industrial improvements not suitable for occupancy / Redevelopment', 'Industrial'),
('43', '01', '43-01', 'Lumber yards, Sawmills, Planing Mills', 'Industrial'),
('43', '99', '43-99', 'Lumber Yard / Mill improvements not suitable for occupancy / Redevelopment', 'Industrial'),
('44', '01', '44-01', 'Packing Plants', 'Industrial'),
('44', '02', '44-02', 'Fruit and Vegetable Packing Plants', 'Industrial'),
('44', '03', '44-03', 'Meat Packing Plants', 'Industrial'),
('44', '99', '44-99', 'Packing Plant improvements not suitable for occupancy / Redevelopment', 'Industrial'),
('45', '01', '45-01', 'Canneries', 'Industrial'),
('45', '02', '45-02', 'Fruit and Vegetable processing', 'Industrial'),
('45', '03', '45-03', 'Bottlers and Brewers', 'Industrial'),
('45', '04', '45-04', 'Distillers', 'Industrial'),
('45', '99', '45-99', 'Use code 45 improvements not suitable for occupancy / Redevelopment', 'Industrial'),
('46', '01', '46-01', 'Food Processing', 'Industrial'),
('46', '02', '46-02', 'Bakeries', 'Industrial'),
('46', '03', '46-03', 'Candy Factories', 'Industrial'),
('46', '04', '46-04', 'Potato Chip Factories', 'Industrial'),
('46', '99', '46-99', 'Use code 46 improvements not suitable for processing / Redevelopment', 'Industrial'),
('47', '01', '47-01', 'Mineral Plants', 'Industrial'),
('47', '02', '47-02', 'Cement / Asphalt Plants', 'Industrial'),
('47', '03', '47-03', 'Rock and Gravel Plants', 'Industrial'),
('47', '04', '47-04', 'Refineries', 'Industrial'),
('47', '99', '47-99', 'Use code 47 improvements not suitable for occupancy / Redevelopment', 'Industrial'),
('48', '01', '48-01', 'Warehousing', 'Industrial'),
('48', '02', '48-02', 'Warehouse - Mini Storage (open)', 'Industrial'),
('48', '03', '48-03', 'Warehouse - Mini Storage ( enclosed)', 'Industrial'),
('48', '04', '48-04', 'Warehouse - Metal', 'Industrial'),
('48', '05', '48-05', 'Warehouse - CBS constructed Airport Hangar w/o Office space', 'Industrial'),
('48', '06', '48-06', 'Warehouse - CBS constructed Airport Hangar w/ separate Office space more than 30% of building sqft', 'Industrial'),
('48', '07', '48-07', 'Warehouse - Truck Terminal', 'Industrial'),
('48', '08', '48-08', 'Warehouse - Distribution', 'Industrial'),
('48', '09', '48-09', 'Warehouse - Flex', 'Industrial'),
('48', '10', '48-10', 'Warehouse - Retail', 'Industrial'),
('48', '11', '48-11', 'Warehouse - Cold Storage', 'Industrial'),
('48', '12', '48-12', 'Warehouse - Utility Building', 'Industrial'),
('48', '13', '48-13', 'Misc. value on separate folio i.e., fence, slab (not paving)', 'Industrial'),
('48', '14', '48-14', 'Warehouse - Telecommunication Switch Station', 'Industrial'),
('48', '15', '48-15', 'Warehouse - Metal Airport Hangar', 'Industrial'),
('48', '99', '48-99', 'Warehouse improvements not suitable for occupancy / Redevelopment', 'Industrial'),
('49', '01', '49-01', 'Open Storage - new and used building supplies', 'Industrial'),
('49', '02', '49-02', 'Junk Yards', 'Industrial'),
('49', '03', '49-03', 'Auto Wrecking', 'Industrial'),
('49', '04', '49-04', 'Fuel Storage', 'Industrial'),
('49', '05', '49-05', 'Equipment and Materials Storage', 'Industrial'),
('49', '99', '49-99', 'Use code 49 improvements not suitable for occupancy / Redevelopment', 'Industrial'),
('50', '01', '50-01', 'Improved Agriculture', 'Agricultural'),
('50', '02', '50-02', 'Improved Agriculture, curtilage with residence', 'Agricultural'),
('50', '03', '50-03', 'Improved Agriculture, curtilage with manufactured home', 'Agricultural'),
('50', '04', '50-04', 'Improved Agriculture, with manufactured home on personal property', 'Agricultural'),
('50', '05', '50-05', 'Improved Agriculture, with barn / garage', 'Agricultural'),
('50', '06', '50-06', 'Improved Agriculture with commercial business', 'Agricultural'),
('50', '99', '50-99', 'Improved Agriculture not suitable for occupancy / Redevelopment', 'Agricultural'),
('51', '01', '51-01', 'Cropland Soil Capability Class I', 'Agricultural'),
('51', '02', '51-02', 'Cropland Soil Capability Class I with residence', 'Agricultural'),
('51', '03', '51-03', 'Cropland Soil Capability Class I with manufactured home', 'Agricultural'),
('51', '04', '51-04', 'Cropland Soil Capability Class I with manufactured home on personal property', 'Agricultural'),
('51', '05', '51-05', 'Cropland Soil Capability Class I with barn / garage', 'Agricultural'),
('51', '06', '51-06', 'Cropland Soil Capability Class I with commercial business', 'Agricultural'),
('51', '99', '51-99', 'Cropland Soil Capability Class I improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('52', '01', '52-01', 'Cropland Soil Capability Class II', 'Agricultural'),
('52', '02', '52-02', 'Cropland Soil Capability Class II with residence', 'Agricultural'),
('52', '03', '52-03', 'Cropland Soil Capability Class II with manufactured home', 'Agricultural'),
('52', '04', '52-04', 'Cropland Soil Capability Class II with manufactured home on personal property', 'Agricultural'),
('52', '05', '52-05', 'Cropland Soil Capability Class II with barn / garage', 'Agricultural'),
('52', '06', '52-06', 'Cropland Soil Capability Class II with commercial business', 'Agricultural'),
('52', '99', '52-99', 'Cropland Soil Capability Class II improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('53', '01', '53-01', 'Cropland Soil Capability Class III', 'Agricultural'),
('53', '02', '53-02', 'Cropland Soil Capability Class III with residence', 'Agricultural'),
('53', '03', '53-03', 'Cropland Soil Capability Class III with manufactured home', 'Agricultural'),
('53', '04', '53-04', 'Cropland Soil Capability Class III with manufactured home on personal property', 'Agricultural'),
('53', '05', '53-05', 'Cropland Soil Capability Class III with barn / garage', 'Agricultural'),
('53', '06', '53-06', 'Cropland Soil Capability Class III with commercial business', 'Agricultural'),
('53', '99', '53-99', 'Cropland Soil Capability Class III improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('54', '01', '54-01', 'Timberland - site index 90 & above', 'Agricultural'),
('54', '06', '54-06', 'Timberland - site index 90 & above with commercial business', 'Agricultural'),
('55', '01', '55-01', 'Timberland - site index 80-89', 'Agricultural'),
('55', '06', '55-06', 'Timberland - site index 80-89 with commercial business', 'Agricultural'),
('56', '01', '56-01', 'Timberland - site index 70-79', 'Agricultural'),
('56', '06', '56-06', 'Timberland - site index 70-79 with commercial business', 'Agricultural'),
('57', '01', '57-01', 'Timberland - site index 60-69', 'Agricultural'),
('57', '06', '57-06', 'Timberland - site index 60-69 with commercial business', 'Agricultural'),
('58', '01', '58-01', 'Timberland - site index 50-59', 'Agricultural'),
('58', '06', '58-06', 'Timberland - site index 50-59 with commercial business', 'Agricultural'),
('59', '01', '59-01', 'Timberland not classified by site index to pines', 'Agricultural'),
('59', '06', '59-06', 'Timberland not classified by site index to pines with commercial business', 'Agricultural'),
('60', '01', '60-01', 'Grazing Land Soil Capability Class I', 'Agricultural'),
('60', '02', '60-02', 'Grazing Land Soil Capability Class I with residence', 'Agricultural'),
('60', '03', '60-03', 'Grazing Land Soil Capability Class I with manufactured home', 'Agricultural'),
('60', '04', '60-04', 'Grazing Land Soil Capability Class I with manufactured home on personal prop.', 'Agricultural'),
('60', '05', '60-05', 'Grazing Land Soil Capability Class I with barn / garage', 'Agricultural'),
('60', '06', '60-06', 'Grazing Land Soil Capability Class I with commercial business', 'Agricultural'),
('60', '99', '60-99', 'Grazing Land Soil Capability Class I improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('61', '01', '61-01', 'Grazing Land Soil Capability Class II', 'Agricultural'),
('61', '02', '61-02', 'Grazing Land Soil Capability Class II with residence', 'Agricultural'),
('61', '03', '61-03', 'Grazing Land Soil Capability Class II with manufactured home', 'Agricultural'),
('61', '04', '61-04', 'Grazing Land Soil Capability Class II with manufactured home on personal prop.', 'Agricultural'),
('61', '05', '61-05', 'Grazing Land Soil Capability Class II with barn / garage', 'Agricultural'),
('61', '06', '61-06', 'Grazing Land Soil Capability Class II with commercial business', 'Agricultural'),
('61', '99', '61-99', 'Grazing Land Soil Capability Class II improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('62', '01', '62-01', 'Grazing Land Soil Capability Class III', 'Agricultural'),
('62', '02', '62-02', 'Grazing Land Soil Capability Class III with residence', 'Agricultural'),
('62', '03', '62-03', 'Grazing Land Soil Capability Class III with manufactured home', 'Agricultural'),
('62', '04', '62-04', 'Grazing Land Soil Capability Class III with manufactured home on personal prop.', 'Agricultural'),
('62', '05', '62-05', 'Grazing Land Soil Capability Class III with barn / garage', 'Agricultural'),
('62', '06', '62-06', 'Grazing Land Soil Capability Class III with commercial business', 'Agricultural'),
('62', '99', '62-99', 'Grazing Land Soil Capability Class III improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('63', '01', '63-01', 'Grazing Land Soil Capability Class IV - cattle', 'Agricultural'),
('63', '02', '63-02', 'Grazing Land Soil Capability Class IV - cattle with residence', 'Agricultural'),
('63', '03', '63-03', 'Grazing Land Soil Capability Class IV - cattle with manufactured home', 'Agricultural'),
('63', '04', '63-04', 'Grazing Land Soil Capability Class IV - cattle with MH on personal prop.', 'Agricultural'),
('63', '05', '63-05', 'Grazing Land Soil Capability Class IV - cattle with barn / garage', 'Agricultural'),
('63', '06', '63-06', 'Grazing Land Soil Capability Class IV - horses', 'Agricultural'),
('63', '07', '63-07', 'Grazing Land Soil Capability Class IV - horses with residence', 'Agricultural'),
('63', '08', '63-08', 'Grazing Land Soil Capability Class IV - horses with manufactured home', 'Agricultural'),
('63', '09', '63-09', 'Grazing Land Soil Capability Class IV - horses with MH on personal prop.', 'Agricultural'),
('63', '10', '63-10', 'Grazing Land Soil Capability Class IV - horses with barn / garage', 'Agricultural'),
('63', '11', '63-11', 'Grazing Land Soil Capability Class IV - goats', 'Agricultural'),
('63', '12', '63-12', 'Grazing Land Soil Capability Class IV - goats with residence', 'Agricultural'),
('63', '13', '63-13', 'Grazing Land Soil Capability Class IV - goats with manufactured home', 'Agricultural'),
('63', '14', '63-14', 'Grazing Land Soil Capability Class IV - goats with MH on personal prop.', 'Agricultural'),
('63', '15', '63-15', 'Grazing Land Soil Capability Class IV - goats with barn / garage', 'Agricultural'),
('63', '16', '63-16', 'Grazing Land Soil Capability Class IV - sheep', 'Agricultural'),
('63', '17', '63-17', 'Grazing Land Soil Capability Class IV - sheep with residence', 'Agricultural'),
('63', '18', '63-18', 'Grazing Land Soil Capability Class IV - sheep with manufactured home', 'Agricultural'),
('63', '19', '63-19', 'Grazing Land Soil Capability Class IV - sheep with MH on personal prop.', 'Agricultural'),
('63', '20', '63-20', 'Grazing Land Soil Capability Class IV - sheep with barn / garage', 'Agricultural'),
('63', '26', '63-26', 'Grazing Land Soil Capability Class IV - cattle with commercial business', 'Agricultural'),
('63', '27', '63-27', 'Grazing Land Soil Capability Class IV - horses with commercial business', 'Agricultural'),
('63', '28', '63-28', 'Grazing Land Soil Capability Class IV - goats with commercial business', 'Agricultural'),
('63', '29', '63-29', 'Grazing Land Soil Capability Class IV - sheep with commercial business', 'Agricultural'),
('63', '99', '63-99', 'Grazing Land Soil Capability Class IV improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('64', '01', '64-01', 'Grazing Land Soil Capability Class V', 'Agricultural'),
('64', '02', '64-02', 'Grazing Land Soil Capability Class V with residence', 'Agricultural'),
('64', '03', '64-03', 'Grazing Land Soil Capability Class V with manufactured home', 'Agricultural'),
('64', '04', '64-04', 'Grazing Land Soil Capability Class V with manufactured home on personal prop.', 'Agricultural'),
('64', '05', '64-05', 'Grazing Land Soil Capability Class V with barn / garage', 'Agricultural'),
('64', '06', '64-06', 'Grazing Land Soil Capability Class V with commercial business', 'Agricultural'),
('64', '99', '64-99', 'Grazing Land Soil Capability Class V improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('65', '01', '65-01', 'Grazing Land Soil Capability Class VI', 'Agricultural'),
('65', '02', '65-02', 'Grazing Land Soil Capability Class VI with residence', 'Agricultural'),
('65', '03', '65-03', 'Grazing Land Soil Capability Class VI with manufactured home', 'Agricultural'),
('65', '04', '65-04', 'Grazing Land Soil Capability Class VI with MH on personal property', 'Agricultural'),
('65', '05', '65-05', 'Grazing Land Soil Capability Class VI with barn / garage', 'Agricultural'),
('65', '06', '65-06', 'Grazing Land Soil Capability Class VI with commercial business', 'Agricultural'),
('65', '99', '65-99', 'Grazing Land Soil Capability Class VI improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('66', '01', '66-01', 'Orchard Groves', 'Agricultural'),
('66', '02', '66-02', 'Orchard Groves with residence', 'Agricultural'),
('66', '03', '66-03', 'Orchard Groves with manufactured home', 'Agricultural'),
('66', '04', '66-04', 'Orchard Groves with manufactured home on personal property', 'Agricultural'),
('66', '05', '66-05', 'Orchard Groves with barn / garage', 'Agricultural'),
('66', '06', '66-06', 'Orchard Groves with commercial business', 'Agricultural'),
('66', '99', '66-99', 'Orchard Groves improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('67', '01', '67-01', 'Poultry', 'Agricultural'),
('67', '02', '67-02', 'Poultry with residence', 'Agricultural'),
('67', '03', '67-03', 'Poultry with manufactured home', 'Agricultural'),
('67', '04', '67-04', 'Poultry with manufactured home on personal property', 'Agricultural'),
('67', '05', '67-05', 'Poultry with barn / garage', 'Agricultural'),
('67', '06', '67-06', 'Tropical Fish', 'Agricultural'),
('67', '07', '67-07', 'Tropical Fish with residence', 'Agricultural'),
('67', '08', '67-08', 'Tropical Fish with manufactured home', 'Agricultural'),
('67', '09', '67-09', 'Tropical Fish with manufactured home on personal property', 'Agricultural'),
('67', '10', '67-10', 'Tropical Fish with barn / garage', 'Agricultural'),
('67', '11', '67-11', 'Bees', 'Agricultural'),
('67', '12', '67-12', 'Bees with residence', 'Agricultural'),
('67', '13', '67-13', 'Bees with manufactured home', 'Agricultural'),
('67', '14', '67-14', 'Bees with manufactured home on personal property', 'Agricultural'),
('67', '15', '67-15', 'Bees with barn / garage', 'Agricultural'),
('67', '21', '67-21', 'Miscellaneous Agriculture', 'Agricultural'),
('67', '22', '67-22', 'Miscellaneous Agriculture with residence', 'Agricultural'),
('67', '23', '67-23', 'Miscellaneous Agriculture with manufactured home', 'Agricultural'),
('67', '24', '67-24', 'Miscellaneous Agriculture with manufactured home on personal property', 'Agricultural'),
('67', '25', '67-25', 'Miscellaneous Agriculture with barn / garage', 'Agricultural'),
('67', '26', '67-26', 'Poultry with commercial business', 'Agricultural'),
('67', '27', '67-27', 'Tropical Fish with commercial business', 'Agricultural'),
('67', '28', '67-28', 'Bees with commercial business', 'Agricultural'),
('67', '29', '67-29', 'Miscellaneous Agriculture with commercial business', 'Agricultural'),
('67', '99', '67-99', 'Use code 67 improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('68', '01', '68-01', 'Dairies, Feed Lots', 'Agricultural'),
('68', '02', '68-02', 'Dairies, Feed Lots with residence', 'Agricultural'),
('68', '03', '68-03', 'Dairies, Feed Lots with manufactured home', 'Agricultural'),
('68', '04', '68-04', 'Diaries, Feed Lots with manufactured home on personal property', 'Agricultural'),
('68', '05', '68-05', 'Dairies, Feed Lots with barn / garage', 'Agricultural'),
('68', '06', '68-06', 'Dairies, Feed Lots with commercial business', 'Agricultural'),
('68', '99', '68-99', 'Use code 68 improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('69', '01', '69-01', 'Ornamentals, miscellaneous agriculture', 'Agricultural'),
('69', '02', '69-02', 'Ornamentals, miscellaneous agriculture with residence', 'Agricultural'),
('69', '03', '69-03', 'Ornamentals, miscellaneous agriculture with manufactured home', 'Agricultural'),
('69', '04', '69-04', 'Ornamentals, miscellaneous agriculture with MH on personal property', 'Agricultural'),
('69', '05', '69-05', 'Ornamentals, miscellaneous agriculture with barn / garage', 'Agricultural'),
('69', '06', '69-06', 'Ornamentals, miscellaneous agriculture with commercial business', 'Agricultural'),
('69', '99', '69-99', 'Use code 69 improvements not suitable for occupancy / Redevelopment', 'Agricultural'),
('70', '01', '70-01', 'Vacant Institutional', 'Institutional'),
('70', '02', '70-02', 'Vacant Institutional with extra features', 'Institutional'),
('71', '01', '71-01', 'Churches', 'Institutional'),
('71', '02', '71-02', 'Church with residence', 'Institutional'),
('71', '03', '71-03', 'Church with parsonage', 'Institutional'),
('71', '04', '71-04', 'Church Administration Building', 'Institutional'),
('71', '05', '71-05', 'Church - recreational', 'Institutional'),
('71', '99', '71-99', 'Church improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('72', '01', '72-01', 'School - private', 'Institutional'),
('72', '02', '72-02', 'School - private, church owned', 'Institutional'),
('72', '03', '72-03', 'College - private', 'Institutional'),
('72', '04', '72-04', 'Day Care / Nursery', 'Institutional'),
('72', '05', '72-05', 'Day Care / Nursery - prior residence', 'Institutional'),
('72', '06', '72-06', 'Pre school - private', 'Institutional'),
('72', '07', '72-07', 'Pre school - private - prior residence', 'Institutional'),
('72', '08', '72-08', 'Fraternity or Sorority home', 'Institutional'),
('72', '99', '72-99', 'School improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('73', '01', '73-01', 'Hospital - privately owned', 'Institutional'),
('73', '02', '73-02', 'Hospital - Re-Hab', 'Institutional'),
('73', '99', '73-99', 'Hospital improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('74', '01', '74-01', 'Homes for the aged', 'Institutional'),
('74', '02', '74-02', 'Independent Living Facilities', 'Institutional'),
('74', '03', '74-03', 'Assisted Living Facilities', 'Institutional'),
('74', '04', '74-04', 'Assisted Living Facilities - prior residence', 'Institutional'),
('74', '05', '74-05', 'Assisted Living Facilities - prior multi family', 'Institutional'),
('74', '06', '74-06', 'Continuing Care Retirement Communities (CCRC''s)', 'Institutional'),
('74', '99', '74-99', 'Use code 74 improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('75', '01', '75-01', 'Orphanages', 'Institutional'),
('75', '02', '75-02', 'Orphanages - prior residence', 'Institutional'),
('75', '03', '75-03', 'Other non-profit or charitable services', 'Institutional'),
('75', '04', '75-04', 'Residential HOA', 'Institutional'),
('75', '05', '75-05', 'Condominium HOA', 'Institutional'),
('75', '06', '75-06', 'Townhouse HOA', 'Institutional'),
('75', '07', '75-07', 'Commercial / Industrial HOA', 'Institutional'),
('75', '99', '75-99', 'Use code 75 improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('76', '01', '76-01', 'Mortuaries / Funeral Homes', 'Institutional'),
('76', '02', '76-02', 'Cemeteries - privately owned', 'Institutional'),
('76', '03', '76-03', 'Cemeteries - government owned', 'Institutional'),
('76', '04', '76-04', 'Crematoriums', 'Institutional'),
('76', '99', '76-99', 'Use code 76 improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('77', '01', '77-01', 'Clubs', 'Institutional'),
('77', '02', '77-02', 'Lodges', 'Institutional'),
('77', '03', '77-03', 'Union Halls', 'Institutional'),
('77', '99', '77-99', 'Clubs / Lodges / Union Halls improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('78', '01', '78-01', 'Sanitariums', 'Institutional'),
('78', '02', '78-02', 'Convalescent & Rest Homes', 'Institutional'),
('78', '03', '78-03', 'Convalescent & Rest Homes - prior residence', 'Institutional'),
('78', '04', '78-04', 'Nursing Homes', 'Institutional'),
('78', '05', '78-05', 'Nursing Homes - prior residence', 'Institutional'),
('78', '06', '78-06', 'Re-Hab Living Facilities', 'Institutional'),
('78', '07', '78-07', 'Re-Hab Living Facilities - prior residence', 'Institutional'),
('78', '99', '78-99', 'Use code 78 improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('79', '01', '79-01', 'Cultural organizations, facilities', 'Institutional'),
('79', '99', '79-99', 'Cultural organizations, facilities improvements not suitable for occupancy / Redevelopment', 'Institutional'),
('80', '01', '80-01', 'Vacant Governmental', 'Government'),
('80', '02', '80-02', 'Vacant Governmental with extra features', 'Government'),
('80', '99', '80-99', 'Vacant Governmental not suitable for occupancy/Redevelopment', 'Government'),
('81', '01', '81-01', 'Military', 'Government'),
('82', '01', '82-01', 'Forest, parks, recreational areas - Federal', 'Government'),
('82', '02', '82-02', 'Forest, parks, recreational areas - State', 'Government'),
('82', '03', '82-03', 'Forest, parks, recreational areas - County', 'Government'),
('82', '04', '82-04', 'Forest, parks, recreational areas - Municipal', 'Government'),
('83', '01', '83-01', 'Public Schools', 'Government'),
('83', '02', '83-02', 'Public Schools - elementary', 'Government'),
('83', '03', '83-03', 'Public Schools - middle', 'Government'),
('83', '04', '83-04', 'Public Schools - high school', 'Government'),
('83', '99', '83-99', 'Public Schools improvements not suitable for occupancy / Redevelopment', 'Government'),
('84', '01', '84-01', 'Colleges', 'Government'),
('84', '99', '84-99', 'College improvements not suitable for occupancy / Redevelopment', 'Government'),
('85', '01', '85-01', 'Hospitals - municipal owned', 'Government'),
('85', '02', '85-02', 'Hospitals - county owned', 'Government'),
('85', '03', '85-03', 'Hospitals - state owned', 'Government'),
('85', '04', '85-04', 'Hospitals - district owned', 'Government'),
('85', '99', '85-99', 'Hospitals improvements not suitable for occupancy / Redevelopment', 'Government'),
('86', '01', '86-01', 'County owned land - vacant (not included in other codes)', 'Government'),
('86', '02', '86-02', 'County owned land - improved (not included in other codes)', 'Government'),
('86', '03', '86-03', 'County Administration Bldg.', 'Government'),
('86', '04', '86-04', 'County Public Works / Utility', 'Government'),
('86', '05', '86-05', 'County Corrections Facility', 'Government'),
('86', '06', '86-06', 'County Courthouse', 'Government'),
('86', '07', '86-07', 'County Police / Fire Station', 'Government'),
('86', '17', '86-17', 'County Administration Single Story Office Bldg', 'Government'),
('86', '18', '86-18', 'County Administration Single Multi Story Office Bldg', 'Government'),
('86', '99', '86-99', 'County improvements not suitable for occupancy / Redevelopment', 'Government'),
('87', '01', '87-01', 'State owned land - vacant (not included in other codes)', 'Government'),
('87', '02', '87-02', 'State owned land - improved (not included in other codes)', 'Government'),
('87', '03', '87-03', 'State Administration Bldg.', 'Government'),
('87', '04', '87-04', 'State Public Works / Utility', 'Government'),
('87', '05', '87-05', 'State Corrections Facility', 'Government'),
('87', '17', '87-17', 'State Administration Single Story Office Bldg', 'Government'),
('87', '18', '87-18', 'State Administration Single Multi Story Office Bldg', 'Government'),
('87', '99', '87-99', 'State improvements not suitable for occupancy / Redevelopment', 'Government'),
('88', '01', '88-01', 'Federal owned land - vacant (not included in other codes)', 'Government'),
('88', '02', '88-02', 'Federal owned land - improved (not included in other codes)', 'Government'),
('88', '03', '88-03', 'Federal Administration Bldg.', 'Government'),
('88', '04', '88-04', 'Federal Corrections Facility', 'Government'),
('88', '05', '88-05', 'Federal Courthouse', 'Government'),
('88', '06', '88-06', 'Post Office - Federal Owned', 'Government'),
('88', '17', '88-17', 'Federal Administration Single Story Office Bldg', 'Government'),
('88', '18', '88-18', 'Federal Administration Single Multi Story Office Bldg', 'Government'),
('88', '99', '88-99', 'Federal improvements not suitable for occupancy / Redevelopment', 'Government'),
('89', '01', '89-01', 'Municipal owned land - vacant (not included in other codes)', 'Government'),
('89', '02', '89-02', 'Municipal owned land - improved (not included in other codes)', 'Government'),
('89', '03', '89-03', 'Municipal Administration Bldg.', 'Government'),
('89', '04', '89-04', 'Municipal Public Works / Utility', 'Government'),
('89', '05', '89-05', 'Municipal Police / Fire Station', 'Government'),
('89', '06', '89-06', 'Post Office - Municipal Owned', 'Government'),
('89', '17', '89-17', 'Municipal Administration Single Story Office Bldg', 'Government'),
('89', '18', '89-18', 'Municipal Administration Single Multi Story Office Bldg', 'Government'),
('89', '99', '89-99', 'Municipal improvements not suitable for occupancy / Redevelopment', 'Government'),
('90', '01', '90-01', 'Leasehold Interest Govt. prop -vacant (leased by a non-governmental lessee)', 'Vacant Land'),
('90', '02', '90-02', 'Leasehold Interest Govt. prop.-improved (leased by a non-governmental lessee)', 'Vacant Land'),
('91', '01', '91-01', 'Utility, gas companies - vacant', 'Vacant Land'),
('91', '02', '91-02', 'Utility, gas companies - improved', 'Vacant Land'),
('91', '03', '91-03', 'Utility, electric companies - vacant', 'Vacant Land'),
('91', '04', '91-04', 'Utility, electric companies - improved', 'Vacant Land'),
('91', '05', '91-05', 'Utility, telephone and telegraph - vacant', 'Vacant Land'),
('91', '06', '91-06', 'Utility, telephone and telegraph - improved', 'Vacant Land'),
('91', '07', '91-07', 'Locally Assessed Railroads', 'Vacant Land'),
('91', '08', '91-08', 'Water and Sewer Service', 'Vacant Land'),
('91', '09', '91-09', 'Pipelines', 'Vacant Land'),
('91', '10', '91-10', 'Utility - canal', 'Vacant Land'),
('91', '11', '91-11', 'Radio, television, cellular phone communication towers', 'Vacant Land'),
('91', '99', '91-99', 'Use code 91 improvements not functional or suitable for occupancy / Redevelopment', 'Vacant Land'),
('92', '01', '92-01', 'Mining lands, petroleum lands, gas lands', 'Vacant Land'),
('93', '01', '93-01', 'Subsurface rights', 'Vacant Land'),
('94', '01', '94-01', 'Right of Way - Street, Road, etc. - Public', 'Vacant Land'),
('94', '02', '94-02', 'Right of Way - Street, Road, etc. - Private', 'Vacant Land'),
('94', '03', '94-03', 'Right of Way - drainage / irrigation, water retention', 'Vacant Land'),
('94', '04', '94-04', 'Conservation Easement', 'Vacant Land'),
('95', '01', '95-01', 'Submerged Lands', 'Vacant Land'),
('95', '02', '95-02', 'River / Canal', 'Vacant Land'),
('95', '03', '95-03', 'Lakes', 'Vacant Land'),
('95', '04', '95-04', 'Ponds', 'Vacant Land'),
('95', '05', '95-05', 'Bay', 'Vacant Land'),
('96', '01', '96-01', 'Environmentally sensitive land', 'Vacant Land'),
('96', '02', '96-02', 'Sewage disposal', 'Vacant Land'),
('96', '03', '96-03', 'Solid waste', 'Vacant Land'),
('96', '04', '96-04', 'Borrow pit', 'Vacant Land'),
('96', '05', '96-05', 'Drainage reservoirs', 'Vacant Land'),
('96', '06', '96-06', 'Waste lands', 'Vacant Land'),
('96', '07', '96-07', 'Marsh', 'Vacant Land'),
('96', '08', '96-08', 'Sand dunes', 'Vacant Land'),
('96', '09', '96-09', 'Swamps', 'Vacant Land'),
('96', '10', '96-10', 'Composting', 'Vacant Land'),
('97', '01', '97-01', 'Outdoor recreation or park land subject to classified use assessment', 'Vacant Land'),
('98', '01', '98-01', 'Centrally assessed', 'Vacant Land'),
('99', '01', '99-01', 'Acreage not zoned agriculture', 'Vacant Land')
ON CONFLICT (full_code) DO UPDATE SET
  description = EXCLUDED.description,
  category = EXCLUDED.category;
