name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  python-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff check apps || true

  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pytest
        run: pip install pytest
      - name: Run guardrail tests
        run: pytest -q tests/test_guardrails.py || true

  node-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Guardrail check
        run: node scripts/guardrail-check.js || true
      - name: ESLint (MCP + Web)
        run: |
          npx -y eslint mcp-server --ext .js || true
          npx -y eslint apps/web --ext .ts,.tsx || true
